- context.ts
- dev.ts
- editor.tsx
- import_map.json
- live.tsx
- src/AddNewComponent.tsx
- src/ComponentPreviewList.tsx
- src/Editor.tsx
- src/EditorSidebar.tsx
- src/icons/PlusIcon.tsx
- src/ui/Button.tsx
- src/ui/JSONSchemaForm.tsx
- src/ui/Modal.tsx
- src/ui/hooks/useTrapFocus.tsx
- src/useEditorForm.tsx
- types.ts
- utils/component.ts
The Live Editor, already has a way to add components, but the user doesn't have enough information about the component, because he/she only sees the component label. It would be good to have a component preview to improve the UX.
To achieve this new UX, this PR adds a Component List Modal, that renders all components and islands from a project inside a modal. 
The shape of the response:
```ts
interface ComponentPreview {
link: string;
component: string; // Relative path to components/islands
componentLabel: string; // schema.title or component relative path.
}
interface Output { islands: ComponentPreview[], components: ComponentPreview[] }
```
> ⚠️ The project that uses this version needs to add `"tabbable": "https://esm.sh/v91/tabbable@5.3.3/",` entry to its import_map.json
> feat: List Components Preview

- README.md
- scripts/copyPartytownFiles.ts
The partytown plugin needs the lib files to instantiate the service worker/web worker, but the partytown copy files CLI doesn't work with Deno.
Live exports createPartytownFiles script that creates partytown files at the destination folder passed from the user.
To accomplish this, the script fetches the partytown files from https://unpkg.com/browse/@builder.io/partytown@0.7.0/lib/ folder and saves them in the destination folder.
The unpkg doesn't handle list files from a folder, so, the files are hard coded for instance.
> feat: Parytown copy files script

- editor.tsx
- src/EditorSidebar.tsx
- src/ui/JSONSchemaForm.tsx
- src/useEditorForm.tsx
To be more compatible with the JSON Schema the RenderField component should handle the format, required, and type from JSON Schema.
This feature was motivated by the SEO/Metatag component schema: https://github.com/deco-pages/start/pull/6 .
Now the RenderField component maps the JSON Schema format and checks if the property is required.
1. The form handles the discard, and the save button with the native submit;
2. The discard button doesn't reload the page. Now, the button resets the form state with the components value from the server.
1. useEditorOperations edit the components (renamed as initialComponents) prop via componentsRef, and this may be root cause of bugs. Now the componentsRef.current has a copy of the components (initialComponents), so the components value won't be changed.
> feat: Improve Form fields to handle JSON Schema format

- canvas.tsx
- live.tsx
This PR adds a new behavior to live. When fetch('/live/api/components'), the renderer will render:
```
return ctx.render({
components: [{key: `./components/${component}`, label: '', uniqueId: '', props: {}}],
loaders: []
});
```
This way, we can accomplish screens like:
> feat: Live components

- import_map.json
- live.tsx
- utils/filesystem.ts
This PR adds a new api for retrieving components:
`/live/api/components` returns the components list in json format 
```
{
name: string // label
path: string // component relative path to root
link:string // vscode link path
}
```
`/live/api/components?component={}` renders that component in a context
> feat: Retrieve components list

- live.tsx
- pages.ts
- utils/component.ts
- utils/schema.ts
- utils/supabase.ts
This PR adds <Editor/> component to the component viewer. 
The ideia behind this PR is to create a fake page for each component where the only component on that page is the component being edited. This is ok for now because it allows us to reuse many components created for editing the pages.
The mechanism used for rendering components is the same one used for rendering pages. fetch `/?component={componentName}` for getting a page rendered for that component. If the page component already exists on the database, this page is returned. A new fake page is returned if it doesn't exist on the database. This fake page will be persisted on the database once the user clicks on "Save Draft".
These component pages are created under the path `/_live/components/{ComponentName}.tsx`
> feat: Add component editor

- live.tsx
- pages.ts
- types.ts
- utils/supabase.ts
This PR completes Live routing capabilities for dynamic routes (e.g: `/:slug/p`), without the need to manually add those routes to the project. It also organizes some functions.
It uses the very handy [URLPattern](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern/exec) web API, which Fresh internally also uses it via [rutt](https://deno.land/x/rutt@0.0.13).
One implication we have is that now **we're fetching all production routes for every render**, which can be optimized later. I took a look at the measures and couldn't notice any difference (the timings vary a lot for `loadPage`).
**Before:**
**After:**
--
There was also some changes in `fetchPageFromId` after I realized that, even for those cases, we'd still need the page's URL to generate params because some …
> Implementing dynamic routing using URLPattern

- .vscode/settings.json
- live.tsx
This PR improves `live` feedback by removing a console.log we did to a better formatted terminal:
Before/After can be seen below:
> feat: Terminal aesthetics

- pages.ts
Test running 30 times to get data on supabase.
```ts
// before
await client
.from("pages")
.select("id, name, data, path, state")
.eq("site", siteId)
.eq("archived", false)
.is("flag", null);
// after
await client
.from("pages")
.select("id, name, data, path, state")
.eq("site", siteId)
.eq("state", "published");
const res = (performance.now() - begin);
```
Before:
|  media |  p90  | p95  | p99 | 
| --- | --- | --- | --- |
| 127.0514385333333 | 144.73032150000006 | 150.68236399999978 | 297.68789 |
After:
|  media |  p90  | p95  | p99 | 
| --- | --- | --- | --- |
| 118.03299983333332 | 125.51731000000007 | 137.7168929999998 | 259.58971399999996 |
> chore: Use new state for fetch pages and avoid going on db twice

- components/CoreWebVitals.tsx
- live.tsx
This PR adds web-vitals report to all live sites.
It uses Google's web vitals library to add reporting to all sites. A nice thing is that it's integrated with our `pages` data, so we can cross reference web vitals to page ids and page path templates
To upgrade your site, just bump your live's version in your import_map.json
To know more: https://www.loom.com/share/f517456700124677b453745daa37dbcf
> feat: Web Vitals

- components/LiveAnalytics.tsx
- components/LivePage.tsx
- live.ts
This PR makes two things:
1. Renames CoreWebVitals component to LiveAnalytics for better naming fit
2. add siteId to the analytics so we know which metric is coming from which site
3. Fix some typings on a few files
> feat: Add site id to analytics dimention

- components/LiveAnalytics.tsx
- components/LivePage.tsx
This PR adds site_id, page_id and page_path to all events sent to jitsu. This will allow us to properly filter events on our dashboard
> feat: Add site_id to metrics

- live.ts
- pages.ts
When using the page editor with loaders we had an error being thrown because the data being returned to the editor already had the loaders resolved. This PR addresses this issue by creating a custom function for editor data
> fix: editor with loaders

- std/ui/components/Image.tsx
- std/ui/components/Picture.tsx
This PR fixes a lighthouse warning of the picture element. Also, moves the preload globally to the picture element. To preload an image, just
```tsx
<Picture preload >
<Picture.Source src="..." />
<Picture.Source src="..." />
<Picture/>
```
> fix: legacy api usage with picture element

- components/LiveAnalytics.tsx
Currently, web-vitals script is being imported before onLoad. This makes the browser wait for this script to trigger the onLoad event. This may lead to bad load times for us. Since web-vitals is not necessary for the first paint, it can be deferred after the onload event.
> chore: Improve load time

- components/LiveControls.tsx
This PR drops heroicons from live in favor of tabler-icons since heroicons does not tree-shake well, drastically increasing bundle sizes.
> chore: drop heroicons

- components/LivePage.tsx
We don't need to check if we're in production to include the `<LiveControls` island, since its code already hides the component selector:
[Código do LiveControls](https://github.com/deco-cx/live/blob/db5db5c8be254460d1c56534f265520dc3b3a2c9/components/LiveControls.tsx)
[Exemplo de loja com essa mudança](https://deco-sites-fashion-62dh7r5h2s60.deno.dev/)
> Enabling LiveControls in production (fixes scroll to section)

- utils/page.ts
- utils/schema/transform.ts
This PR adds a new type for function types called `live-function`. With this, we are able to create a custom widget for adding and validating functions on the editor
> feat: Use live-function as function type on json schema

- utils/schema/transform.ts
This PR makes it possible to declare fixed-length arrays using JSDoc. 
Example: Take the following schema:
```tsx
export interface Props {
pairs: string[]
}
```
suppose you want to make the `pairs` array to have a fixed length of value 2. To accomplish this, now you can:
```tsx
export interface Props {
/**
* @minItems 2
* @maxItems 2
*/
pairs: string[]
}
```
It also works if you specify ranges and other. For more info, follow the JSON Schema spec
> fix: format to the right format jsdoc

- utils/schema/transform.test.ts
- utils/schema/transform.ts
On a JSON Schema non required types should accept null as a valid (empty) value.
> Fix props to use "null" as valid type on non-required types.

- live.ts
- pages.ts
This PR moves the editorData from the middleware to the page handler. After these changes, adding a `?editorData` to the end of the url, makes the client to receive editorData after flag engine logic
> fix: editor data respect flag selection

- flags.ts
- live.ts
- types.ts
This PR persists flags on cookies by creating one cookie per flag. 
The cookie value is the base64 of the flag object. Also, The mechanism used for invalidating the flag is by checking the last time the flag was updated. If it was updated after the cookie was set, the matcher will be rerun.
> feat: persist flags

- std/ui/components/Image.tsx
This PR changes the strategy from DPR to `dimension * factor`. By doing this solves the problem that happens when set width and the image/video is rendered on a bigger screen with higher width and the screen have DPR 1. Also, it is backward compatible with DPR strategy.
> feat: Drop DPR in favor of manual rescale factor

- dev.ts
- utils/schema/transform.ts
- utils/schema/utils.ts
+ not throw error when generating schemas for empty files
Related: https://github.com/deco-sites/deco/pull/172
> Regenerate manifest if only schema has changed

- deps.ts
- dev.ts
- types.ts
- utils/page.ts
- utils/schema/transform.ts
- utils/schema/utils.ts
After #106, deco-sites/deco stopped working with an error saying json-schema is of unknown type `dts`. This PR addresses this issue by importing only necessary types from json-schema and re-exporting them as our version of JSONSchema.
> fix: remove json-schema from deps and import it directly

- live.ts
- pages.ts
- utils/http.ts
- utils/manifest.ts
This PR allows loaders to return headers and status. These headers and statuses are merged following an heuristic. The only headers allowed are cache-control and vary headers. 
When multiple loaders return a cache-control header on the same page, their cache-control headers must be merged. We use the more specific value first. This means that if we have two loaders returning two different cache-control headers, say `max-age=60, public, stale-while-revalidate=60` and `max-age=0, private, must-revalidate`, the final cache-control header should be `max-age=0, private, must-revalidate, stale-while-revalidate=60`
This PR adds a default cache-control to all pages: `max-age=0, s-maxage=60, public, stale-while-revalidate=3600, stale-if-error: 86400`. This value will change in case a loader …
> feat: Add header response side effect to loaders

- engine/core/mod.ts
- engine/schema/builder.ts
- engine/schema/merge.ts
Add schema builder. It is used to build the final JSONSchema definitions used on manifest.
```ts
export interface SchemaBuilder {
/**
* Returns the schema data raw
*/
data: SchemaData;
/**
* Build the final schema.
* @param base the current directory.
* @param namespace the current repository namespace.
* @returns the built Schemas.
*/
build(base: string, namespace: string): Schemas;
/**
* Merge with other schema (provided to a third-party manifest)
*/
mergeWith(other: Schemas): SchemaBuilder;
/**
* Add a new block schema to the schema.
* @param blockSchema is the refernece to the configuration input and the blockfunction output
*/
withBlockSchema(blockSchema: BlockModule | EntrypointModule): SchemaBuilder;
}
```
The schema builder allows you to add new block schemas in the final …
> [Live@v1] Add schema builder

- pages.ts
- types.ts
- utils/manifest.ts
Global sections are special pages (state=global) which contain 1 section and have a page path that starts with `/_live/workbench/sections/`
This PR allows pages to have a section with a key that points to a global section, which is then replaced with the contents of the section in the "global" page at `/_live/workbench/sections/:section`
Next PR: at the admin, to allow saving arbitrary sections from the library.
> Add support for global sections

- components/LiveAnalytics.tsx
- components/LiveControls.tsx
- utils/timings.ts
This PR is linked to https://github.com/deco-sites/admin/pull/239 and sends WebVitals metrics parent window when `window !== top`. Also, it adds some console info when developing on localhost: 
To remove it from being shown, click on "levels" and remove "info" from chrome's dev tools
> feat: send metrics to iframe

- components/LiveControls.tsx
Navigates to admin with current page path encoded in the url.
When clicking with a `.`, we would redirect the user to `/admin/${window.LIVE.site.id}/pages/${window.LIVE.page.id}`. After the changes proposed on this PR, we are now redirecting the user to:
```ts
/admin/${window.LIVE.site.id}/pages/${window.LIVE.page.id}?pagePath=${window.location.pathname}${window.location.search}
```
> feat: navigate to admin with page path encoded

- blocks/utils.ts
- engine/block.ts
- engine/introspect.ts
- engine/schema/builder.ts
- engine/schema/gen.ts
- engine/schema/utils.ts
- routes/_middleware.ts
This PR adds a new response to context. This response is copied when generating the final response. So, setting set-cookie headers on this response will lead to setting the response cookie of the server
> feat: set-cookies for loaders/actions

- engine/configstore/fs.ts
- engine/configstore/provider.ts
- handlers/proxy.ts
- live.gen.ts
- matchers/MatchOrigin.ts
- schemas.gen.json
This Pr adds two new blocks:
1. Proxy handler
Proxy requests to a specified url
2. MatchOrigin
A matcher that test regex or include against the header `origin`
Also, it adds support for local testing.
1. clone the [fashion](https://github.com/deco-sites/fashion) store
2. run `USE_LOCAL_STORAGE=true deno task start`
Navigate to your `localhost:8000` again and you should be able to see the google homepage.
> Proxy handler

- clients/withManifest.ts
- routes/live/invoke/[...key].ts
- routes/live/invoke/index.ts
As title says, we were receiving a null response from invoke. This caused the `fetch().then(response => response.json())` break with the error `Uncaught (in promise) SyntaxError: Unexpected end of JSON input`
After this change, we return a `null` as json, so the aforementioned issue is fixed
> fix: Unexpected end of JSON input on Invoke

- components/LivePageEditor.tsx
- engine/core/resolver.ts
- pages/LivePage.tsx
- sections/PageInclude.tsx
- sections/UseSlot.tsx
This PR improves the Inline Editor:
- Handles outside block
- Use Slot sections
- Fixes resolve chain (https://github.com/deco-cx/live.ts/pull/226/commits/2bf9385fd6439962ded9a39540531e0d62a525d7)
> feat: Inline Editor handle outside block and slot sections

- engine/block.ts
- pages/LivePage.tsx
- sections/PageInclude.tsx
- sections/UseSlot.tsx
Avoid coupling untyped props between UseSlot and PageInclude with LivePage
> chore: Pass renderSection via context

- flags/audience.ts
- handlers/proxy.ts
- schemas.gen.json
Previously names with whitespace are allowed but isn't a valid cookie so browser complains about.
> Allow only valid cookie names on audience name

- components/JsonViewer.tsx
Fix Firefox JSON viewer.
In Firefox, the Link element onload triggered before onload was set.
> Fix Firefox json viewer.

- dev.ts
- engine/fresh/manifest.ts
Now you can run `deno run -A dev.ts --gen-only` and your project will not trigger the `main.ts` start
> Add gen-only mod

- engine/core/mod.ts
This fixes a bug where the "propsIsResolved" flag is passed all the way for the inner resolve calls.
> Fix inner resolve options should not be reused

- engine/releases/fs.ts
- engine/schema/reader.ts
- scripts/order_imports.ts
- scripts/release.ts
- utils/namespace.ts
- utils/stringifyForWrite.ts
- utils/update.ts
While developing a site I've realised that `deno fmt` adds a newline to end of every tracked git file. Since the logic here does not add newlines to end of JSON.strinfigy before adding it to a file, it is not following the format commited to the repository.
This is a small nuisance and since I'm trying things out decided to try and fix it.
Before:
- Clone a repo which uses deco
- Run `deno task start`
- Run `git diff` or `git status` and notice that there's a whitespace removed at the end of `schemas.gen.json`
- Run `deno fmt`
- Run `git diff` or `git status` and notice that such space is gone
After:
- Clone a repo which uses deco
- Run `deno task start`
- Run `git diff` or `git status` and see that there's no change
The video demonstrates those versions: …
> Add a newline when writing stringified JSONs

- blocks/app.ts
- blocks/route.ts
- clients/withManifest.ts
- engine/block.ts
- engine/core/mod.bench.ts
- engine/core/mod.test.ts
- engine/core/mod.ts
- engine/core/resolver.ts
- engine/core/utils.ts
- engine/fresh/defaults.ts
- engine/fresh/manifest.ts
- mod.ts
- plugins/deco.ts
- routes/_middleware.ts
- scripts/apps/templates/app.mod.ts.ts
- types.ts
- utils/sync.ts
Previously, it wasn't possible to use the manifest from defendant apps because it requires the self evaluation first. Now, when resolving dependencies the resolved dependencies will be available to resolve current app dependencies.
> Allow extending resolvables and resolvers in runtime

- blocks/app.ts
- scripts/apps/dev.ts
- scripts/apps/templates/app.mod.ts.ts
App name is no longer necessary as this is used only to fetch doccache
> Remove references to appName

- engine/schema/transform.ts
- live.gen.ts
TsLiteralType can have slashs from types defined by files. We remove those slashs to avoid issues related on how RJSF defines/search for refs on a schema.
> Remove slash from TSLiteralTypes

- engine/schema/transform.ts
The current behavior involves an issue where TSTypes containing strings as keys are not being properly evaluated during transformation.
```
export interface Theme = {
"base-100": string,
primary: string,
}
```
Will generate an schema where `Theme` has only the `primary` property.
As a result of this, the generated schema for the Theme interface only includes the primary property.
This PR addresses this concern by rectifying the behavior. It ensures that both string properties are also processed appropriately during schema generation.
> Allow string literals as keys on object from tsTypeElements.

- blocks/app.ts
- blocks/route.ts
- blocks/utils.tsx
- clients/proxy.ts
- clients/withManifest.ts
- import_map.json
- routes/live/invoke/index.ts
- scripts/apps/serve.ts
- scripts/apps/templates/app.mod.ts.ts
- scripts/apps/templates/deno.json.ts
- scripts/apps/templates/deps.ts.ts
- scripts/apps/templates/import_map.json.ts
- types.ts
- utils/update.ts
Big improvements around DevX using invoke:
previously:
```ts
ctx.invoke("$live/actions/secrets/encrypt.ts", {})
```
Now:
```ts
const result = await ctx.invoke.$live.actions.secrets.encrypt({})
```
This change is backwards compatible because the invoke itself is a function.
Also you can batch requests using the same signature
```ts
const {cart} = await ctx.invoke({
cart: ctx.invoke.vtex.loaders.cart({}),
})
```
This is only possible because `InvokeAwaiter` implements `PromiseLike` so we can defer the trigger of the request until the `await` is used, in case of batching the function will return the payload.
PS: Took the opportunity to add a `serve.ts` app command (sorry for the mess)
> Add new manifest proxy utilities

- blocks/function.ts
- blocks/handler.ts
- blocks/route.ts
- blocks/workflow.ts
- engine/manifest/manifest.ts
- handlers/fresh.ts
- handlers/routesSelection.ts
- handlers/workflowRunner.ts
- observability/http.ts
- observability/labels.ts
- observability/observe.ts
- plugins/deco.ts
- routes/[...catchall].tsx
- routes/_middleware.ts
- routes/live/_meta.ts
- routes/live/invoke/[...key].ts
- routes/live/invoke/index.ts
- routes/live/previews/[...block].tsx
- routes/live/release.ts
- routes/live/workflows/run.ts
- types.ts
- I've decreased the cardinality of blocks metrics by decreasing the number of buckets and removing unnecessary information 
- Added http latency tracking
- Expose routePath for outer middlewares to be used as a observability metrics
- Renamed a Type from LiveConfig to DecoState
> Expose path template & add observability on middlewares

- blocks/app.ts
- blocks/appsUtil.ts
- engine/middleware.ts
Now you can export a middleware function that intercepts any invoke to any of your block functions, e.g.:
Export the function into any `apps/*.ts` file and check the result
```ts
export const middleware = (props, ctx) => {
console.log(props, ctx.resolveChain);
return ctx.next();
}
```
> Apps middleware

- blocks/utils.tsx
- routes/_middleware.ts
When a search return 0 products, some SEO agencies demand the page return to be 404 as response status.
In antive vtex stores not found PDPs return 404 as a reponse status (legacy and storefront)
This PR add Status in ctx to be editable by loader.
Use Case: 
Do a invalid search
in inline loader, check the product return length
if 0, change the status to 404 with `ctx.response.status`
> feat: add response status editable by loader

- blocks/section.ts
- engine/schema/transform.ts
This PR allow users to require specific sections instead of the generic one keeping backwards compatibility. Currently this is possible using `BlockInstance<"BLOCK STRING", Manifest>` the problem with this approach is because the string is strictly required so you cannot swap out using another section that has the same "semantic" behavior. Also, using the block address `deco-sites/storefront/sections/MySection.tsx` prevents the code to be used as template since the name of the template is used, thus the site based on such template will not inherit the same name as template does. So, for instance, if you create a site from storefront the `MySection.tsx` needs to be renamed to `deco-sites/YOUR_SITE/sections/MySection.tsx`, so it will require changing the sourecode.
```tsx
// …
```
> Accepting specific sections using its type

- observability/otel/config.ts
This pr simply adds a service instance on OTEL attributes, making possible to distinguish between isolates instances
> Add service instance id on Resource attributes for OTEL

- blocks/loader.ts
- blocks/route.ts
- blocks/utils.tsx
- clients/proxy.ts
- clients/withManifest.ts
- engine/core/mod.bench.ts
- engine/core/mod.test.ts
- engine/core/mod.ts
- engine/core/resolver.ts
- engine/schema/comments.ts
- handlers/fresh.ts
- handlers/routesSelection.ts
- routes/_middleware.ts
- routes/live/_meta.ts
- routes/live/invoke/index.ts
- routes/live/previews/[...block].tsx
- runtime/caches/common.ts
- runtime/caches/denoKV.ts
- runtime/fetch/mod.ts
- utils/log.ts
- utils/timings.ts
This pull request introduces enhancements to loaders by incorporating stale caching and improved visibility. 
The architecture of Deco.cx relies on the assumption that utilizing stale caching for third-party datasources yields optimal performance and facilitates customization. In practical terms, our custom `fetch` function ensures that all requests are routed through a stale caching CDN layer. For example, when a user writes `fetch('https://example.com')`, Deco.cx's framework actually fetches the proxied URL: `fetch('https://decocache.com?src=https://example.com')`. While this approach initially worked well for integrations on `decohub`, challenges arose as some services offered their own client packages that did not support a custom fetch. Additionally, instrumenting these fetches for …
> feat: Caching loaders

- utils/invoke.ts
Output streaming on loaders doesn't not add new lines after each object. This breaks expected behavior on client, where each object is separated by new line.
> Add new line on output stream after each object.

- blocks/app.ts
- blocks/loader.ts
- engine/manifest/defaults.ts
- routes/live/invoke/[...key].ts
- routes/live/invoke/index.ts
This PR does mainly two things:
1 - Avoid catching errors on invoke resolver
Why? because sometimes you're invoking a function inline (e.g from another function action/loader) and the response should't be an HTTPError, instead the invoke response should be kept. On the other hand the invoke HTTP API handler should always return an HTTP error. so it will be fine to move to there.
2 - Avoid overriding resolvers with app dependencies
This is specially useful when you're in a migration process and you have two apps with the same name (we have this in our admin) and some of the apps defines the same action/loader. This is making the "main app" (the app that depends on others) overrides the "dependants" apps actions/loaders
> Do not catch invoke err on invoke resolver (instead catch on API handler)

- components/section.tsx
this fixes an error that throws when saved sections are rendered together multiple times in the same page
> Add render count distinct on manifest id

- blocks/section.ts
- engine/block.ts
- engine/schema/transform.ts
This fixes this problem:
scenario
```ts
// MyCustomSection.tsx
type MyCustomSection = JSX.Element;
interface Props {}
export function loader(p: Props) {}
export default function Section(): MyCustomSection {}
```
```ts
// some block that only receives section<MyCustomSection>;
import { Section } from "deco/blocks/section.ts";
interface Props {
section: Section<MyCustomSection>
}
export default function Block(p: Props) {}
```
Before:
the schema of property section of Block will be an array with { title: "MyCustomSection" }
After:
the schema of property section of block will be an array with {title: "MyCustomSection"} and schema of props from `MyCustomSection.tsx`
> feat: schema generation handle chose function return types as array

- runtime/caches/s3.ts
Change key with the goal of having varied object's prefix to avoid aws throttling.
> change s3 key format

- blocks/loader.ts
- blocks/section.ts
This PR makes async rendering work with islands.
The issue was that Async Rendering creates a Proxy object. When this object was passed to Islands directly, Fresh's serializer tried to JSON.stringify this proxy object, that throw resulting in an error being shown to the final user. The fix was to enable JSON.stringify for this Proxy object so that the ErrorFallbacks catch these errors correctly
> fix: Islands and Async Rendering

- runtime/caches/fileSystem.ts
This warning gets spammed all over HyperDx, and this information is basically representing a miss, which is already contained in the cache hit metric.
> Remove warning when file not found

- engine/schema/schemeable.test.ts
- engine/schema/schemeable.ts
- engine/schema/transform.ts
Currently we you have default values set in your component you got an empty form in the admin but the component still being rendered with the data specified at code. This leads in bad experience because you can't do the mapping from the input text to the page data.
From now on, you can specify default props (only simpler scenarios are covered) in your block (any block is supported) by just specifying it in the function parameter itself. Example:
```tsx
import { ImageWidget } from "apps/admin/widgets.ts";
import Image from "apps/website/components/Image.tsx";
interface Props {
href?: string;
image?: ImageWidget;
alt?: string;
width?: number;
height?: number;
text?: string;
}
function Footer({
image =
"https://ozksgdmyrqcxcwhnbepg.supabase.co/storage/v1/object/public/assets/4959/d7aa9290-074 …
```
> Simple default props version

- engine/errors.ts
Now you can only use "/test" to redirect. Before this pr you needed to send the complete url. 
before:
```js
redirect(`${url.origin}/test`) 
redirect(new URL(`${url.origin}/test`)
```
after:
```js
redirect(/test) 
redirect(`${url.origin}/test`)
redirect(new URL(`${url.origin}/test`)
```
> [ Erros/Feat ] Redirects

- engine/core/hints.ts
- runtime/fresh/routes/render.tsx
If we have a `asResolved` object, but we pass this to  `ctx.state.resolve({})`, we get the data as the response. However, this breaks async rendering since we need these asResovled to keep as Resolved after calling ctx.state.resolve.
This bug can be seen in our searchbar, where the loader is loaded asResovled, but after the section re-renders, we get the data, instead of the asResovled loader
> fix resolved

- blocks/section.ts
- components/section.tsx
- deno.json
Enables https://github.com/deco-cx/apps/pull/721 (SingleDeferred.tsx) abort signal to render section fallback
Related to issue/milestone https://github.com/deco-cx/community/issues/13
> feat: throw if aborted while rendering section

- blocks/loader.ts
This PR fixes the vary so the __cb cache key takes into account the loader cache key even if the loader cache is not enabled
> fix: useSection hook cache key

- blocks/section.ts
revert from this https://github.com/deco-cx/deco/commit/2f8658c9bbe7f3fb04267cd74b9c88b0f4f9a31f to this https://github.com/deco-cx/deco/commit/223b2a27d68f559c6cf53f7a77992ba18231fe52.
This fixes the section return type match with the page [SEO property](https://github.com/deco-cx/apps/blob/main/website/pages/Page.tsx#L45).
> fix: section export default return type

- daemon/git.ts
When one creates a branch with `git checkout -b`, git returns the following
This means tracking is null. In this case, let's take main as the default tracking branch. A future PR may add a better heuristics for finding the tracking branch
> fix: autofind tracking branch

- runtime/routes/invoke.ts
> fix: try json when no content length is supplied

- runtime/middleware.ts
For some (akward) reason, hono deletes `content-type` if set response is not fresh (meaning everytime that any middleware runs). This leads in `headers are immutable` error when certain conditions like redirects or websocket connections. So i'm first setting it to undefined to make sure response is always fresh.
> [Hono fix] Set response to undefined to force not deleting headers

- daemon/async.ts
- daemon/git.ts
- daemon/main.ts
- daemon/realtime/app.ts
- daemon/worker.ts
- deno.json
- engine/decofile/fsFolder.ts
- utils/sync.ts
Uses read-write lock to make sure there's one single git operation happening on the server.
When I'll use any git api, I do lock.wlock, to acquire a write lock. This makes sure one single request is being performed by the whole daemon set apis
When I'll use any other daemon apis, I do lock.rlock, to make sure many concurrent daemon apis can be used.
Also, I acquire the read lock for generating the manifest and metadata
> fix: rebase

- daemon/worker.ts
I was using the #769 in production but there were some issues on preview. Also, this doesn't harm rebase, so I guess it's ok for now to remove this lock
> chore; Allow worker without rlock

- blocks/loader.ts
This pr enables sites that uses websites/sections/Rendering/Lazy.tsx to cache their responses even if ENABLE_LOADER_CACHE is false.
> fix(loader): prevent sections not being cached when ENABLE_LOADER_CACHE is false

- .github/workflows/publish.yaml
> fix: use deno user permissions for deno-dir

- blocks/loader.ts
This pr enables sites that uses websites/sections/Rendering/Lazy.tsx to cache their responses even if ENABLE_LOADER_CACHE is false.
> feat(loader): allow loader bypass cache and but allow sections being cached

- clients/withManifest.ts
Introduces the `shouldDecodeChunk` parameter to `readFromStream` for conditional decoding of stream chunks. Default behavior remains unchanged unless shouldDecodeChunk is set to false.
- Default Behavior: If `shouldDecodeChunk` is `true` or not provided, the function behaves as before, decoding the chunk with `decodeURIComponent`.
- New Flexibility: If `shouldDecodeChunk` is `false`, the chunk will bypass decoding, allowing for direct JSON parsing.
> feat: add shouldDecodeChunk to readFromStream

- .github/workflows/publish.yaml
- blocks/page.tsx
- blocks/utils.tsx
- clients/proxy.ts
- clients/withManifest.ts
- components/JsonViewer.tsx
- components/section.tsx
- deco.ts
- deno.json
- deps.ts
- engine/core/resolver.ts
- hooks/useDevice.ts
- hooks/usePartialSection.ts
- hooks/useScript.ts
- hooks/useSection.ts
- observability/otel/metrics.ts
- runtime/caches/mod.ts
- runtime/errors.ts
- runtime/features/invoke.ts
- runtime/features/styles.css.ts
- runtime/fetch/mod.ts
- runtime/handler.tsx
- runtime/htmx/Bindings.tsx
- runtime/mod.ts
- runtime/routes/entrypoint.tsx
- utils/object.ts
- utils/timings.ts
Issue #790 
In order to deal with the slow types errors,attempted to address them by adding explicit type annotations into the files where the problem occurs. 
I tried this approach and resolved 38 out of 41 issues. However, three errors persist. We can solve that in another PR.
> Adding return types to avoid compilation errors

- clients/withManifest.ts
Current forApp type doesn't define invoke as a result of a proxy invoke.
A proxied invoke is a bigger type, since it is able to proxy the Manifest of an App.
By extending the forApp type of return, we allow the return type of proxied calls to be also applied.
> fix client forApp to allow invokation proxy

- blocks/matcher.ts
- runtime/errors.ts
Return type of shortcircuit was defined as HTTPError, `export const shortcircuit = (resp: Response): HTTPError`. This return type defines that the function return something and that we should expect HTTPError as a type.
Moreover, is correct to define never as the expected behavior.
```
export const shortcircuit = (resp: Response): never => {
throw new HttpError(resp);
};
```
> Fix shortcircuit return type

- blocks/page.tsx
- blocks/utils.tsx
- components/JsonViewer.tsx
- components/section.tsx
- deco.ts
- hooks/useDevice.ts
- hooks/usePartialSection.ts
- hooks/useScript.ts
- runtime/features/invoke.ts
- runtime/fetch/mod.ts
- runtime/handler.tsx
- runtime/routes/entrypoint.tsx
Creating good documentation for functions and symbols using JSDocs.
Issue: #815
> Adding JSDocs for all public symbols

- daemon/meta.ts
fix release issue from https://github.com/deco-cx/deco/commit/d037f3ad26b553ee8e47cfb7c9bf27612774fb09
```
error: Failed resolving types. Relative import path "deco/engine/block.ts" not prefixed with / or ./ or ../ and not in import map from "<...>/deco/daemon/meta.ts"
```
> chore: fix import issues related to publish on JSR

- dev/deno.ts
- dev/tailwind.ts
This PR fixes some path checking on recursive importing that are related to local apps.
Before this fix, when running on windows a lot of classes were removed because the `resolveRecursively` was skipping the local app path since `path.includes(localAppsFolder)` was comparing different type of separators and the import wasn't occurring
> fix: windows path checking

- engine/schema/comments.ts
- engine/schema/schemeable.test.ts
- engine/schema/schemeable.test.types.ts
With this PR, anonymous type definitions with jsdocs like this will work
```ts
interface WithAnonTypes {
/**
* @title Cards
*/
items: {
title: string;
/**
* @format rich-text
*/
description: string;
buttons: Array<{
label: string;
/**
* @format url
*/
url: string;
position: "left" | "right" | "center";
}>;
}[];
}
```
> JsDocs in anonymous types

- blocks/flag.ts
The variant was return the objext instead the right value. This could break the website, so, I fix to return the right type
> Fix - Flag

- blocks/matcher.ts
- hooks/useDevice.ts
- runtime/caches/mod.test.ts
- runtime/routes/invoke.ts
This PR allow create functions to variate cookie name of the matchers. For example: [https://github.com/deco-cx/apps/pull/966](https://github.com/deco-cx/apps/pull/966)
> add session key

- blocks/action.ts
- blocks/appsUtil.ts
- blocks/loader.ts
- blocks/matcher.ts
- clients/proxy.ts
- components/section.tsx
- daemon/git.ts
- engine/core/mod.ts
- engine/core/resolver.ts
- engine/core/utils.ts
- engine/decofile/provider.ts
- engine/importmap/jsr.ts
- engine/manifest/manifestBuilder.ts
- engine/schema/builder.ts
- engine/schema/comments.ts
- engine/schema/lazy.ts
- engine/schema/transform.ts
- engine/schema/utils.ts
- observability/otel/config.ts
- observability/otel/instrumentation/deno-runtime.ts
- observability/otel/logger.ts
- observability/otel/metrics.ts
- runtime/errors.ts
- runtime/features/meta.ts
- runtime/middleware.ts
- types.ts
- utils/dataURI.ts
- utils/patched_fetch.ts
- utils/promise.ts
This PR corrects typos and grammar issues in comments and variable names. Additionally, some variables were renamed within their scope to improve readability and clarity.
If you have any questions, feel free to reach out!
Cheers,
Arthur
P.S. Special shoutout to Rafael—the best designer I know! 😎😎
> Fix typos, improve comments, and rename variables for clarity

- runtime/caches/redis.test.ts
- runtime/caches/redis.ts
To avoid waiting too much for a command to be executed, sometimes forever in case of an unresponsive Redis, I added a default timeout of 500ms.
The idea is to try to query Redis and create a race between a `setTimeout` and the command itself. The tests simulate the expected behavior, but they added some delay on the test suite.
> feat: add command timeouts to the redis cache

- blocks/action.ts
- blocks/loader.ts
- blocks/utils.tsx
- deco.ts
- engine/block.ts
- engine/manifest/manifest.ts
- runtime/fresh/plugin.tsx
- runtime/mod.ts
This PR adds the capability of export a access control const `defaultVisibility` that determines if a loader or a action is server only acessible or public accssible. 
A server only accessible loader/action its only callable by ctx.invoke, this prevent exposing private endpoints on webisite calls on client. 
Exemple:
```ts
export const defaultVisibility = 'private'
```
```ts
export const defaultVisibility = 'public'
```
> [FEAT]: create server only access control for loaders and actions

- deco.ts
- observability/otel/config.ts
- runtime/middleware.ts
This PR aims to improves informations on otel and response headers in 2 ways:
- First it will add an otel info to the logs: deployment.environment. That will be the env name with "env-" as prefix to avoid collision when the user decide to use "production" as an environment name, and "production" for the production deployment.
- Second it will add the header x-deco-platform to the fetch, this aims to increase our monitoring system when trying to understand the difference between the platforms.
> Adds environment name to otel and adds platform header to all responses

- daemon/git.ts
This pull request introduces changes that allow submodules to be used seamlessly in the project. The update ensures that repositories with submodules can be properly checked out and utilized without manual intervention.
- Updated the deployment logic to support submodule usage across all environments.
- Improved handling of repository configurations to ensure smooth integration with submodules.
This change helps overcome existing limitations in Deno, particularly its lack of built-in support for submodules and importing from private sources. By enabling seamless submodule usage, we provide a more flexible and reliable workflow for managing complex repositories without depending on external workarounds.
> support for submodules

- .github/workflows/ci.yaml
- blocks/utils.tsx
- utils/http.ts
This PR adds a way to simulate a request as a bot using query params, this is useful for debugging and SEO comparison as it disables async render and some other features.
Using `asBot` param on url `isBot` will always be `true`
> Feat: Simulate a bot request using query params

- hooks/mod.ts
- hooks/useSection.ts
The idea of this is allow websites that uses useSection to ignore some querystrings from useSection cache key, resulting in a stable cache key with better cache hit ratio.
This api `unstable_blockUseSectionHrefQueryStrings` can be used in two ways:
1. hardcoded blocked strings
```ts
// apps/site.ts
import { unstable_blockUseSectionHrefQueryStrings } from "deco/hooks"
unstable_blockUseSectionHrefQueryStrings(["utm_source", "gclid"])
```
2. editable by CMS
```ts
// apps/site.ts
import { unstable_blockUseSectionHrefQueryStrings } from "deco/hooks"
interface SiteProps {
// ... other Props
blockedQs: string[]
}
export default function App({blockedQs}: Props) {
// ... some code
unstable_blockUseSectionHrefQueryStrings(blockedQs);
// ... some code
}
```
> feat: allow ignore querystring from useSection href prop

- hooks/useSection.ts
For this context
BLOCKED_QS =['ranSiteID', 'utm_term', 'utm_medium', 'ranMID']
href: http://localhost:8000/?ranMID=value0&ranSiteID=value&utm_medium=aff&utm_term=term
before: createStableHref(href) http://localhost:8000/?ranSiteID=value&utm_term=term
after: createStableHref(href) // http://localhost:8000/
> fix: createStableHref to remove properly the blocked querystrings

- blocks/loader.ts
- runtime/middleware.ts
- runtime/routes/render.tsx
- utils/vary.ts
Add debug param for async render when `__d` is present on request querystring. The output data has this shape:
```ts
interface LoaderDebugData {
resolver: FieldResolver;
reason: {
cache: LoaderCache;
cacheKeyNull: boolean;
}
}
interface DebugData {
debugData: LoaderDebugData[]; // In future could have more properties here with other object type
}
```
> Add debug for /deco/render request
