live.tsx, utils/serverTimings.ts
The Live handler only fetches pages from the storage with `url.pathname` that's fixed values. A problem exists when you have dynamic routes based on a fresh framework, because the storage should have each URL that matches the dynamic route.
To tackle this problem, the createLivePage receives options parameter with interface `CreateLivePageOptions` and behaves following this pattern:
- if options is empty, the Handler runs default loader that get ComponentData from CMS and passes the loader output to the `ctx.render`.
- if options have a template, then Handler runs default loader considering the `template` and `url.pathname` and passes the loader output to the `ctx.render`.
- if options have a loader, the Handler runs options.loader instead of default loader and passes loader output to the …
=> Add Path Template and loaders to handle dynamic Pages

live.tsx, plugins/ga.ts, plugins/partytown.ts
The partytown plugin need to proxy variables from window, like gtag, dataLayer, fb, jitsu.
Partytown plugin receives PartytownConfig parameter
Remove the ga plugin proxy
=> feat: Handle Partytown config

README.md, editor.tsx, lib/htmltopreact.js, live.tsx, src/icons/CaretDownIcon.tsx, src/icons/PlusIcon.tsx, src/icons/TrashIcon.tsx, types.ts, utils/supabase.ts
There are a lot of changes regarding linting. I've made one giant commit with that, so please review it commit-by-commit
=> [45] Changing reference from 'components' to 'data'

components/LiveControls.tsx, types.ts
=> fix: Typings

live.tsx
This PR transforms the `div` section wrapper into an html 5 `section` element
=> chore: Section on html

live.tsx
There was a bug in the unit being reported by live. This PR fixes the scale factor
=> fix: Timings report

live.tsx, pages.ts, types.ts, utils/component.ts
This feature adds the page state, which can be: "published", "draft", "archived" or "dev" (for workbench, components).
=> feat: Add page state

README.md, std/ui/components/Image.tsx, std/ui/types/Image.ts
This PR adds image capabilities to Live. More info in the readme
=> feat: Add image component

std/ui/components/Image.tsx
There's a problem where the drp 3x is way too big for most devices. Also, lighthouse complains a lot about it and it's very easy to get into a fight with lighthouse with dprs that big. I'm reducing the dpr factors to check if we can achieve better lighthouse results
=> feat: Improve image factors

live.ts
This happens when the handler sets headers as well.
=> Fixing "Headers are immutable" error

README.md, deno.json, scripts/release.ts
=> Creating release task

components/LiveSections.tsx, utils/schema/utils.ts
Required for https://github.com/deco-sites/www/pull/1/files#diff-dd8bceab6d319dce3364f8f081bef27ed722ce04140fe58c1369938e1e68451bL18
=> Adding support for nested sections (no support for loaders yet)

std/commerce/occ/client.ts, std/commerce/occ/transform.ts, std/commerce/occ/types.ts, std/commerce/types.ts
=> Oracle cloud commerce initial implementation

components/LiveAnalytics.tsx
=> Sending flag data to Jitsu in a single column

std/commerce/vtex/transform.ts
=> [VTEX] Passing product's properties as additionalProperty to mapped data

pages.ts
The home page was not correctly being taking into consideration. Now, we take care of this case.
=> fix: Routes ranking

utils/manifest.ts
Prune functions before running so we:
1. Run repeated functions once
2. Only run functions referenced by sections
=> chore: Prune functions

components/LiveAnalytics.tsx, deno.lock
=> feat: add fcp and ttfb

components/LiveAnalytics.tsx
Fixes the annoying issue on admin:
=> fix: jitsu is not a function

components/LiveControls.tsx
Goto is not working due to code not being imported
=> Use redirect on livecontrols.tsx

components/LiveAnalytics.tsx
following great advice from @igorbrasileiro
=> fix: remove elements computation from main

utils/namespace.ts
=> Revert "Fix namespace on git remote from https."

dev.ts
https://github.com/deco-cx/deno-githooks/pull/2
=> chore: enable back githooks for windows

clients/withManifest.ts, types.ts
Now you can create an invoker function based on the key. so:
const myFunction = create('path/to/function')
myFunction('blah')
=> feat: export create invoker

engine/schema/builder.ts, schemas.gen.json
=> Resolvable now checks if __resolveType is not one of the actual functions

blocks/route.ts, flags.ts, handlers/routesSelection.ts
This is not necessary and it is breaking the current timings
=> Remove routes timings

CHANGELOG.md, compatibility/v0/editorData.ts
This pr removes the `dedup` by props that was used to deduplicate functions by its props.
=> Remove dedup by props

blocks/section.ts, blocks/utils.ts, engine/block.ts, handlers/devPage.ts, pages/LivePage.tsx, routes/live/invoke/index.ts, routes/live/previews/[...block].tsx, scripts/upgrade.ts, utils/object.ts
This fixes the page metadata.id, allowing to open the admin by pressing `.`
=> fix: page.id

components/LivePageEditor.tsx
This PR improves LivePageEditor layout:
Mobile
Desktop/Tablet
=> feat: Improve section name and controls layout

components/LivePageShowcase.tsx, pages/LivePage.tsx, routes/live/previews/[...block].tsx, sections/PageInclude.tsx
=> feat: Handle formdata at preview

components/LiveControls.tsx
This PR adds a new scoll to section feature that easy editing on deco
=> feat: scroll into newly edited section

components/LiveControls.tsx, pages/LivePage.tsx, schemas.gen.json
Adds PathTemplate to the querystring so when pressing dot everythign works again
=> fix: make dot work again

clients/withManifest.ts
This allows us to use abort signal for invokes
=> feat: forward init to invoke

components/LiveControls.tsx
This PR is the first on a series of PRs aiming to remove scripts required by the editor from this repo.
This PR adds a new listener that receives a script an evals it. With this, we will be able to inject any script into any preview.
=> feat: add new iframe eval injector function

pages/LivePage.tsx
This PR adds resolve chain to sections to allow us to figure out the full resolve chain while previewing. This will enable us perform better computations on the editor
This should be a relatively safe release since it only adds info to the section
=> feat: Add resolve chain

blocks/matcher.ts, components/LiveAnalytics.tsx, components/LiveControls.tsx, handlers/routesSelection.ts, pages/LivePage.tsx, routes/_middleware.ts, types.ts
Add all flags to window.LIVE global variable so we are able to integrate them with analytics
=> feat: add flags back

blocks/flag.ts, blocks/section.ts, engine/schema/transform.ts, engine/schema/utils.ts, flags/multivariate.ts, pages/LivePage.tsx
Adds:
- jsDoc annotations at some types to improve schema;
- merge jsDoc from child and current node at typeAlias transformation
=> feat: Enriches the Section and Multivariant schemas with jsDoc 

utils/invoke.ts
Allow loaders to return response
=> feat: accept response

engine/releases/supabaseProvider.ts
I don't think it is necessary to have exponential backoff since as much time we have without receiving realtime updates it becomes worse.
=> Try reconnect on refetch

routes/live/invoke/index.ts
hotfix #365  by wrapping only when not batched
=> fix: invoke by wrapping only unwrapped

blocks/route.ts, utils/log.ts
=> Improving logs and logging outgoing requests

runtime/caches/proxy.ts
https://discord.com/channels/985687648595243068/1146456435513897061/1146573848439959565
=> Temporarily disabling in-memory cache for other methods

blocks/app.ts, engine/schema/gen.ts
This powers: https://github.com/deco-cx/apps/pull/16
=> Allow dynamic sourcemaps

runtime/fetch/fetchCache.ts
This PR fixes the error by not trying to cache 206 responses
```TypeError: Response status must not be 206
at Cache.put (ext:deno_cache/01_cache.js:102:13)
at fetchAndCache (https://denopkg.com/deco-cx/deco@1.31.13/runtime/fetch/fetchCache.ts:93:16)
at eventLoopTick (ext:core/01_core.js:183:11)
at async fetch (https://denopkg.com/deco-cx/deco@1.31.13/runtime/fetch/fetchCache.ts:104:23)
at async fetch (https://denopkg.com/deco-cx/deco@1.31.13/runtime/fetch/fetchLog.ts:13:22)
at async e.invoke (https://esm.sh/v131/cockatiel@3.1.1/es2019/cockatiel.mjs:3:3607)
at async execute (https://esm.sh/v131/cockatiel@3.1.1/es2019/cockatiel.mjs:3:10311)
at async fetchSafe (file:///Users/gimenes/Documents/code/apps/utils/fetch.ts:41:20)
at async fetchAPI …
```
=> fix: 206 status code

components/LiveAnalytics.tsx, live.gen.ts
- Add img to live anaylitcs.
- Gens.
=> [WIP] Live Analytics using img as trigger.

runtime/caches/proxy.ts
Disable proxy cache via envVar.
Set ENABLE_DECO_PROXY_CACHE=false to disable proxy cache
=> feat: disable proxy cache

handlers/proxy.ts
https://discord.com/channels/985687648595243068/1153381658129608796/1153404250811011172
=> Passing origin from headers

utils/update.ts
Supports import_map inside deno.json
=> Support for import_map inside deno.json

utils/admin.ts, utils/http.ts
=> Allow admin.deco.cx to preview

blocks/matcher.ts, blocks/route.ts
change to a more friendly name
=> change deco cookie names

scripts/init.ts
Great cheers for https://cliffy.io!
=> fix: start script prompt on windows

engine/manifest/manifest.ts
update deco play domain to `https://play.deco.cx/`
=> feat: update deco play domain

clients/withManifest.ts, live.gen.ts
when invocable functions return response with status code >= 4xx the withManifest get the object that the invocable function returned and set it at `cause` the Error it will throw.
=> chore: return error cause

engine/schema/comments.ts, engine/schema/deps.ts, engine/schema/parser.ts, engine/schema/transform.ts
This version supports typescript 5.2
=> Update deno_ast_wasm version

blocks/loader.ts, engine/core/mod.ts
improves loader report by aways returning a uniqueId for loader
=> feat: improve loader report

scripts/init.ts
=> fix: decofile name

engine/schema/parser.ts
This PR leverages DENO_DIR cached dependencies instead of downloading all of them again, this is not supported by Deno Deploy however, local benchmarks shows up to 5x improvement of schema generation time.
Storefront numbers:
Previously 4s
With this version: 1.2s
Under the hood it uses deno_cache lib WASM version hosted at: https://deno.land/x/deno_cache@0.6.3/mod.ts
=> Use file fetcher when possible

components/section.tsx, hooks/usePartialSection.ts, runtime/fresh/routes/render.ts
Tested with storefront-vtex using the following decofile.json
[decofile.json](https://github.com/deco-cx/deco/files/14315569/decofile.json)
=> Add deco render salt

components/section.tsx, hooks/usePartialSection.ts
This PR improves async rendering by:
1. Adding prefetch to all delayed sections
2. Improving onload heuristics to use intersection observer after onload event
=> feat: Add partials prefetch and improve heuristics

runtime/caches/s3.ts
=> Fix MAX_UNCOMPRESSED_SIZE

blocks/loader.ts, runtime/caches/fileSystem.ts
This PR adds the File System on the K8s as a caching option.
=> Add File System as caching option

.github/workflows/update.yml
I think it would be a great addition to this project to add such a workflow. This would help to keep the codebase up-to-date without breaking anything.
It uses [updater](https://github.com/boywithkeyboard/updater), a tool I wrote last year which is available as CLI or GitHub action. 
It opens a pull request if there are any available updates and it'll also add a note if `deno check` fails after the imports have been updated.
=> Add workflow for automatic dependency updates

blocks/loader.ts, runtime/caches/fileSystem.ts, runtime/caches/mod.ts, runtime/caches/s3.ts, runtime/caches/tiered.ts, runtime/fetch/fetchCache.ts, runtime/fetch/mod.ts
This PR created the tiered cache. A cache that can depend on multiple caches and offer a fallback mechanism between them.
Improvements with this PR:
* Avoid cache cold start when creating a new deploy.
* Make executing the requests the last resort; prefer going and checking in each cache available (way faster).
* Faster websites.
Example:
https://sites-osklenbr-onozcgfeuy.decocdn.com/masculino-casacos?__d=trace-tiered
=> Tiered cache

runtime/context.ts, runtime/fs/mod.ts
=> Revert "Patched deco fetch"

runtime/context.ts, runtime/fs/mod.ts
=> Only use monkey patch when path starts with cwd

runtime/context.ts, runtime/fs/mod.ts
=> Revert "Only use monkey patch when path starts with cwd"

runtime/context.ts, runtime/fs/mod.ts
=> Add missing func bind

runtime/context.ts, runtime/fs/mod.ts
=> Revert "Add missing func bind"

runtime/context.ts, runtime/fs/mod.ts
=> Add missing func bind - round (2)

README.md, runtime/caches/fileSystem.ts, runtime/utils.ts
Title explains all.
A few implementation details:
* [LRU documentation](https://github.com/isaacs/node-lru-cache/blob/main/README.md)
* The LRU has a maximum number of files limit, a maximum size limit, and a TTL.
=> Add LRU for file system cache management

engine/manifest/manifest.ts, runtime/fresh/middlewares/3_main.ts, runtime/utils.ts
fix: new initializeState fn - used in 3_main middleware + on newFakeContext
=> Fix: Matchers running on app install

runtime/context.ts
- This allow users to watch decofile only avoiding to use esbuild and allow coding locally
=> Allow watch decofile only

hypervisor/workers/denoRun.ts, scripts/upgrade.ts
- This allows setting host header.
=> Use http client proxy instead of doing manually

engine/core/resolver.ts
Remove span if an error is thrown.
=> End span on resolver error

hypervisor/hypervisor.ts
Allow jwt check bypass when `BYPASS_JWT_VERIFICATION` is present (for dev purposes)
=> feat: allow bypass jwt verification

blocks/loader.ts, blocks/utils.tsx, engine/decofile/fsFolder.ts, hooks/useSection.ts, runtime/fresh/routes/render.tsx, runtime/utils.ts, utils/encoding.ts
=> Add cache burst on partial section querystring

utils/stat.ts
| Before | After |
|--------|-------|
| ![image](https://github.com/deco-cx/deco/assets/53613091/1514fc35-7cf9-44e7-95bc-0a2fb07a2543) | <img width="283" alt="image" src="https://github.com/deco-cx/deco/assets/53613091/ae16de9e-7b4d-42ab-8bdb-cfbca97f373a"> |
| Probe instantly failed | Probe working correctly |
=> NaN check for stats get method

observability/probes/memory.ts, runtime/caches/mod.ts, runtime/fresh/middlewares/1_contextProvider.ts
=> Remove upstash redis and s3 as they are bundle aggressors

components/section.tsx, hooks/useSection.ts
Add to /deco/render cache burst the deployment id
=> fix: render cache fresh

daemon/daemon.ts, daemon/deps.ts, daemon/git.ts
Uses local git binary if available to expose new apis for being used by the admin
=> feat: Git Hypervisor API

daemon/daemon.ts, daemon/main.ts
Enable to run daemon in standalone mode, so that we don't need to wait for isolate for serving files
=> feat: Standalone mode

daemon/daemon.ts, daemon/deps.ts, daemon/git.ts, daemon/main.ts
=> feat: git hono

daemon/daemon.ts, daemon/git.ts
=> feat: add daemon hono

daemon/tunnel.ts
Improve logs with preview and admin urls: from/to
=> chore: Improve logs

daemon/realtime/app.ts
=> fix: encoding again

runtime/middleware.ts
Prevent break servers that doesn't handle bigger headers (>8k)
=> fix: add server-timing header limit to 2k length

daemon/main.ts
=> chore: exclude node modules from tar

clients/withManifest.ts
Make `readFromStream` options an object.
Before:
```ts
readFromStream(response, false);
```
After:
```ts
readFromStream(response, {
shouldDecodeChunk: false,
});
```
=> refactor: make read from stream options an object

daemon/git.ts, deno.json
TODO: 
1. handle rebase no publish
2. handle detached head state
=> fix: New rebase heuristics 🍻 

daemon/meta.ts
When leaving an environment alone for a long time with no changes, a 408 will occur, triggering a retry for /deco/meta. This will false alarm an `updating` state that will only be recovered when someone changes something. 
This PR fixes this issue by not setting the `updating` state when a 408 occurs, thus not false alarming the user
=> fix: Remove false down alarm when 408 occurs

.github/workflows/issues.yaml, .github/workflows/releaser.yaml, MAINTAINERS.txt, blocks/README.md, engine/core/README.md
This PR enhances the README for the deco runtime's Config Resolver Engine. The changes include:
- **Clarified Concepts**: Improved explanations for key concepts such as Resolvers and Resolvables, making it easier for developers to understand how the engine works.
- **Added Code Examples**: Included TypeScript code snippets to illustrate how Resolvers and Resolvables are defined and used.
- **Introduced Mermaid Diagrams**: Added visual diagrams using Mermaid to explain the resolution algorithm, optimizations introduced in version 1.15.1, and how parallelism is implemented during resolution.
- **Updated Resolution Algorithm**: Provided a step-by-step breakdown of the resolution process, including handling of primitive types, recursive resolution, and error management for dangling …
=> Improve engine/core readme

hooks/useDevice.ts
=> fix: useDevice return type

daemon/fs/api.ts, daemon/meta.ts
fixes https://github.com/deco-cx/deco/issues/844
=> fix(daemon): fs/api get blocktype from meta

daemon/fs/api.ts
issue: https://discord.com/channels/985687648595243068/1288144431857275012/1288144431857275012
=> Remove qs from paths

runtime/caches/fileSystem.ts
=> Remove log from delete file failures

hooks/useSection.ts
=> fix: slow type and duplicated `?` at href

runtime/features/render.tsx
This PR fix the optional paths handling 
more info at [Apps#1094](https://github.com/deco-cx/apps/pull/1094)
https://www.loom.com/share/a51b17205b8f4100ab0280a215503cb7?sid=bc9c30ff-1a2a-45e2-b1eb-fa3461a07781
=> fix: url pattern build to handle optional paths

engine/importmap/builder.ts
Fix resolve `resolve:` specifier.
=> fix: resolve specifier

runtime/features/render.tsx
This reverts commit de60a5e2322177b06f22e53b4aa37d07d1c00129.
=> Revert "fix: url pattern build to handle optional paths (#898)"

daemon/git.ts
Need github admin access token route
=> Allow github app authentication.

daemon/git.ts, daemon/main.ts
This pr is a hotfix, short lived solution, for fix this issue https://github.com/deco-cx/deco/issues/923.
Kill the daemon and children process, and let the infrastructure respawn the daemon, that will respawn the children.
=> fix: private github operations and fetch private packages killing daemon process

daemon/main.ts
fixes the respawn https://github.com/deco-cx/deco/pull/922
=> fix: remove fallback for worker respawn duration

blocks/action.ts
=> feat: add introspection option to action block
